<?php

/**
 * Implements hook_boot().
 */
function classloader_composer_boot() {
  $loader = drupal_classloader();

  // This file is created by composer when installing the dependencies of the logging-component with it.
  // To use it with the allready installed classloader the namespace is registered.
  $map = require DRUPAL_ROOT . '/../vendor/composer/autoload_namespaces.php';

  // changes in api of Classloader between 2.0.x and 2.2.x
  if (method_exists($loader, 'addPrefixes')) {
    $loader->addPrefixes($map);
  } else {
    $loader->registerNamespaces($map);
  }
}
