<?php

/**
 * Retrieves the classloader
 */
function drupal_classloader() {
  static $loader;

  if (!$loader) {
    $autoload_file = DRUPAL_ROOT . '/../vendor/autoload.php';
    if (!file_exists($autoload_file)) {
      throw new \RuntimeException('Composer autoload file not found: ' . $autoload_file);
    }

    $loader = require $autoload_file;
    if (extension_loaded('apc')) {
      $cachedLoader  = new \Symfony\Component\ClassLoader\ApcClassLoader('drupal', $loader);
      $cachedLoader->register();
      $loader->unregister();
    }
  }

  return $loader;
}

/**
 * Implements hook_boot().
 */
function classloader_composer_boot() {
  drupal_classloader();
}

/**
 * Implements hook_init().
 */
function classloader_composer_init() {
  drupal_classloader();
}

/**
 * Implements hook_modules_installed().
 */
function classloader_composer_modules_installed(array $modules) {
  drupal_classloader();
}

/**
 * Implements hook_modules_enabled().
 */
function classloader_composer_modules_enabled(array $modules) {
  drupal_classloader();
}
